# .github/workflows/build.yml

name: CMake

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libgtest-dev
          cd /usr/src/gtest
          sudo cmake .
          sudo make
          sudo cp *.a /usr/lib

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: FacadePattern
          path: build/FacadePattern
